ServerName localhost

ProxyRequests Off
ProxyPreserveHost On

ProxyPass        "/api/" "http://backend:3000/api/" retry=0 timeout=30
ProxyPassReverse "/api/" "http://backend:3000/api/"

<Directory "/usr/local/apache2/htdocs">
    Options -Indexes
    AllowOverride None
    Require all granted
    FallbackResource /index.html
</Directory>
