FROM node:22-alpine AS build

WORKDIR /app

COPY FE/package.json FE/package-lock.json ./
RUN npm ci

COPY FE/ ./

ARG VITE_API_BASE_URL=/api
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

RUN npm run build

FROM httpd:2.4-alpine

RUN sed -i \
    -e 's/^#LoadModule proxy_module/LoadModule proxy_module/' \
    -e 's/^#LoadModule proxy_http_module/LoadModule proxy_http_module/' \
    /usr/local/apache2/conf/httpd.conf

COPY docker/apache-container.conf \
    /usr/local/apache2/conf/extra/pauvi.conf

RUN printf '\nInclude conf/extra/pauvi.conf\n' \
    >> /usr/local/apache2/conf/httpd.conf

COPY --from=build /app/dist/ /usr/local/apache2/htdocs/
